# =============================================================================
# Tests for the backend API.
# =============================================================================


# Get backend status without passing a subscription key. 
# This is the same request as the request of the web test running in application insights.
GET https://{{apimHostname}}/backend/status


###


# Get the backend status using the subscription key of the Function App.
GET https://{{apimHostname}}/backend/status
Ocp-Apim-Subscription-Key: {{functionAppSubscriptionKey}}
Ocp-Apim-Trace: true


###


# Get the backend status using the subscription key of the Logic App.
GET https://{{apimHostname}}/backend/status
Ocp-Apim-Subscription-Key: {{logicAppSubscriptionKey}}
Ocp-Apim-Trace: true
